/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface HastNode {
  type: string
  tagName: string
  properties: HastProperties
  children: Array<HastNode | HastTextNode>
}

export interface HastProperties {
  className: string
}

export interface HastTextNode {
  type: string
  value: string
}

export declare function highlight(code: string, language: Language): string

export declare function highlightHast(code: string, language: Language): HastNode

export declare function highlightTokens(code: string, language: Language): TokensResult

export declare const enum Language {
  JS = 0,
  JSX = 1,
  TS = 2,
  TSX = 3,
  JSON = 4,
  YAML = 5,
  CSS = 6,
  HTML = 7,
  Regex = 8,
  JsDoc = 9,
  C = 10,
  Bash = 11,
  Rust = 12
}

export interface StyleAttr {
  style: string
}

export interface ThemedToken {
  content: string
  offset: number
  htmlAttrs?: StyleAttr
}

export interface TokensResult {
  tokens: Array<Array<ThemedToken>>
}
